source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

#Front End Tools
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'simple_form'
gem 'font-awesome-sass', '~> 4.4.0'

#Other
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder


#omniauth for facebook
gem 'omniauth'
gem 'omniauth-facebook', '~> 2.0'


# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'annotate'
  gem 'spring'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end
